---
title: "data_1"
author: "Yan Li"
date: "2025-04-02"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Influenza SEIR Model with Vaccination 

# 1. Load Required Package
library(deSolve)
library(ggplot2)

# 2. Define the SEIR Model Function
seir_model = function(t, state, parameters) {
  with(as.list(c(state, parameters)), {
    # Total population
    N = Su + Sv + Lu + Lv + Iu + Iv + Ru + Rv

    # Force of infection (lambda)
    lambda = (Iu + Iv) / N

    # Time-dependent vaccination rate delta(t)
    d = ifelse(t >= 3 & t <= 20, d_val, 0)

    # Differential equations
    dSu = - b * lambda * Su - d * Su
    dSv = - av * b * lambda * Sv + d * Su
    dLu = b * lambda * Su - l * Lu
    dLv = av * b * lambda * Sv - l * Lv
    dIu = l * Lu - g * Iu
    dIv = l * Lv - g * Iv
    dRu = g * Iu
    dRv = g * Iv

    return(list(c(dSu, dSv, dLu, dLv, dIu, dIv, dRu, dRv)))
  })
}

# 3. Set Simulation Time
# Simulate for 36 weeks with 0.1-week time steps
times = seq(0, 36, by = 0.1)

# 4. Define Model Parameters
parameters = c(
  b = 9.1357,     # Infection rate (beta)
  av = 0.2331,    # Vaccine attenuation factor (VE = (1 - av) * 100%)
  l = 3.5,        # Latency rate per week (lambda)
  g = 1,          # Recovery rate per week (gamma)
  d_val = 0.05    # Vaccination rate during active period
)

# 5. Set Initial Conditions
N = 4959968
Iu = 10
Iv = 0
Lu = 20
Lv = 0
Ru = 0
Rv = 0
Su = N - (Iu + Lu + Ru)
Sv = 0

state = c(Su = Su, Sv = Sv, Lu = Lu, Lv = Lv,
           Iu = Iu, Iv = Iv, Ru = Ru, Rv = Rv)

# 6. Solve the ODE System
out = ode(y = state, times = times, func = seir_model, parms = parameters)
out_df = as.data.frame(out)
```


```{r}
# 7. Plot the Simulation Results
plot(out_df$time, out_df$Iu, type = "l", col = "blue", lwd = 2,
     xlab = "Time (weeks)", ylab = "Number of Infected Individuals",
     main = "Influenza Model Simulation: Infected Populations")
lines(out_df$time, out_df$Iv, col = "red", lwd = 2)
legend("topright", legend = c("Unvaccinated Infected (Iu)", "Vaccinated Infected (Iv)"),
       col = c("blue", "red"), lwd = 2)
```




```{r}
# 8. Load Real Data
real_data = read.csv("modeling_data.csv")


```






